/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CaptainsGamesIndexImport } from './routes/captains-games/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CaptainsGamesIndexRoute = CaptainsGamesIndexImport.update({
  id: '/captains-games/',
  path: '/captains-games/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/captains-games/': {
      id: '/captains-games/'
      path: '/captains-games'
      fullPath: '/captains-games'
      preLoaderRoute: typeof CaptainsGamesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captains-games': typeof CaptainsGamesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captains-games': typeof CaptainsGamesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/captains-games/': typeof CaptainsGamesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/captains-games'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/captains-games'
  id: '__root__' | '/' | '/captains-games/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptainsGamesIndexRoute: typeof CaptainsGamesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptainsGamesIndexRoute: CaptainsGamesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/captains-games/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/captains-games/": {
      "filePath": "captains-games/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
